apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-app
  labels:
    app: quotes-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: quotes-app
  template:
    metadata:
      labels:
        app: quotes-app
    spec:
      containers:
        - name: quotes-app
          image: panwoj/quotes-app:7.0
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: quotes-postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quotes-postgres-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: quotes-postgres-config
                  key: postgres_db
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: quotes-hostname-config
                  key: postgres_host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: quotes-postgres-config
                  key: postgres_port
          readinessProbe:
            httpGet:
              path: /quote/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3