apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quotes-app
  name: quotes-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: quotes-app
  replicas: 4
  template:
    metadata:
      name: quotes-app
      labels:
        app: quotes-app
    spec:
      containers:
        - name: quotes-app
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: quotes-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quotes-postgres-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: quotes-config
                  key: postgres_db
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: quotes-hostname-config
                  key: postgres_host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: quotes-config
                  key: postgres_port
          image: panwoj/quotes-app:9.0
#          readinessProbe:
#            httpGet:
#              path: /quote/health
#              port: 8080
#            initialDelaySeconds: 20
#            periodSeconds: 3