apiVersion: v1
kind: Service
metadata:
  labels:
    app: quotes
  name: quotes
spec:
  type: NodePort
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 32222
  selector:
    app: quotes